"""Defines the widget class for displaying properties of a sequence component tree node."""

from PyQt5.Qt import QWidget

from scriptaseq.internal.generated.qt_ui.seq_component_props_widget import Ui_SequenceComponentPropsWidget


class SequenceComponentPropsWidget(QWidget, Ui_SequenceComponentPropsWidget):
  """Widget for displaying properties of a sequence component tree node."""
  
  def __init__(self, undo_stack, seq_component_custom_props_qt_model, parent=None):
    """Constructor.
    undo_stack -- QUndoStack to receive undoable editing commands generated by this widget.
    seq_component_custom_props_qt_model -- SequenceComponentCustomPropsQtModel responsible for some of the display
      functionality for the custom properties table.
    parent -- Parent QObject.
    """
    QWidget.__init__(self, parent)
    self.setupUi(self)
    
    self._undo_stack = undo_stack
    
    self.customPropsTableView.setModel(seq_component_custom_props_qt_model)