"""Defines a tree node type for a sequence component tree."""

from PyQt5.Qt import QMenu, QCoreApplication
from sortedcontainers.sorteddict import SortedDict

from scriptaseq.internal.gui.undo_commands.seq_component_node import SetComponentTypeCommand
from scriptaseq.internal.gui.undo_commands.seq_component_tree import DeleteSequenceComponentTreeNodeCommand, \
  AddSequenceComponentTreeNodeCommand
from scriptaseq.internal.seq_component_tree.component_types import ContainerSequenceComponentType, \
  SUPPORTED_COMPONENT_TYPES
from scriptaseq.named_tree_node import NamedTreeNode


class CustomSequenceComponentPropValue:
  """Represents the value of a custom property attached to a sequence component tree node."""
  
  def __init__(self, value_str, is_expr=False):
    """Constructor.
    value_str -- Property value, as a string.
    is_expr -- Indicates whether value_str should be interpreted as a Python expression (True) or as a raw string
      (False).
    """
    self.value_str = value_str
    self.is_expr = is_expr

class SequenceComponentNode(NamedTreeNode):
  """Class for nodes in a sequence component tree."""
  
  def __init__(self, name, owning_project_tree_node, component_type=ContainerSequenceComponentType,
    instanced_project_tree_node=None):
    """Constructor.
    The constructed node initially has no parent.
    Raises ValueError if the name is invalid, the node cannot be added to the specified parent, or both parent and
    owning_project_tree_node are unspecified.
    name -- Name for the new node.
    component_type -- BaseSequenceComponentType subclass indicating the type of component.
    owning_project_tree_node -- Reference to the project tree node that owns the sequence component tree to which this
      node belongs.
    instanced_project_tree_node -- Reference to the project tree node that this node is instancing, or None if this node
      is not instancing a project tree node.
    """
    super().__init__(name, True)
    
    self.owning_project_tree_node = owning_project_tree_node
    self.component_type = component_type
    self.instanced_project_tree_node = instanced_project_tree_node
    self.custom_props = SortedDict()
  
  def is_in_instance(self):
    """Checks whether this node is part of an instancing subtree."""
    return self.instanced_project_tree_node is not None
  
  def is_instance_root(self):
    """Checks whether this node is the root of an instancing subtree."""
    return self.is_in_instance() and (self.parent is None or self.parent.is_in_instance())
  
  def make_context_menu(self, undo_stack, seq_component_tree_controller, seq_component_node_controller, parent=None):
    """Creates a context menu for this node.
    undo_stack -- QUndoStack that should receive undoable editing commands generated by the menu.
    seq_component_tree_controller -- SequenceComponentTreeController in charge of high-level changes to the sequence
      component tree.
    seq_component_node_controller -- SequenceComponentNodeController in charge of changes to individual nodes in the
      sequence component tree.
    parent -- Parent QObject for the context menu.
    """
    menu = QMenu(parent)

    # Add menu items for changing the component type, if that is allowed.
    if not self.is_in_instance():
      change_type_menu = menu.addMenu(QCoreApplication.translate('SequenceComponentNode', 'Change &Type'))
      def change_type_func_maker(new_component_type):
        def change_type_func():
          undo_stack.push(SetComponentTypeCommand(seq_component_node_controller, self, new_component_type))
        return change_type_func
      for component_type in SUPPORTED_COMPONENT_TYPES:
        change_type_action = change_type_menu.addAction(component_type.get_icon(), component_type.menu_text)
        change_type_action.setEnabled(component_type != self.component_type)
        change_type_action.triggered.connect(change_type_func_maker(component_type))
    
    # Add menu items for creating child nodes, if creating children is allowed.
    if self.can_have_children and not self.is_in_instance():
      add_menu = menu.addMenu(QCoreApplication.translate('SequenceComponentNode', '&Create Child'))
      def add_func_maker(component_type):
        def add_func():
          new_node = SequenceComponentNode(self.suggest_child_name(component_type.node_default_name),
            component_type=component_type, owning_project_tree_node=self.owning_project_tree_node)
          undo_stack.push(AddSequenceComponentTreeNodeCommand(seq_component_tree_controller, new_node, self))
        return add_func
      for component_type in SUPPORTED_COMPONENT_TYPES:
        add_action = add_menu.addAction(component_type.get_icon(), component_type.menu_text)
        add_action.triggered.connect(add_func_maker(component_type))
    
    # Add a menu item for deleting the node, if it can be deleted.
    if self.parent is not None and ((not self.is_in_instance()) or self.is_instance_root()):
      def delete_func():
        undo_stack.push(DeleteSequenceComponentTreeNodeCommand(seq_component_tree_controller, self))
      delete_action = menu.addAction(QCoreApplication.translate('SequenceComponentNode', '&Delete'))
      delete_action.triggered.connect(delete_func)
    
    return menu
  
  def verify_can_add_as_child(self, node):
    super().verify_can_add_as_child(node)
    
    if node.owning_project_tree_node is not self.owning_project_tree_node:
      raise ValueError(
        QCoreApplication.translate('SequenceComponentNode', 'Cannot mix nodes belonging to different sequence component trees'))